# -*- coding: utf-8 -*-
{
    'name': 'Sistemas de comisiones',
    'version': '1.0',
    'description': 'Agrega comisiones en las ventas',
    'summary': 'Agrega comisiones en las ventas',
    'author': 'DGV',
    'website': 'https://github.com/AlfaSystemas5457/commissions',
    'license': 'LGPL-3',
    'category': 'Other Category',
    'depends': [
        'stock',
        'sale',
    ],
    'data': [
        'security/groups_security.xml',
        'security/commission_security.xml',
        'security/ir.model.access.csv',
        'data/precision.xml',
        'data/config_parameter.xml',
        'data/cron.xml',
        'views/config_views.xml',
        'views/res_users_views.xml',
        'views/manu_view.xml',
        'views/commissions_view.xml',
        'views/plans_view.xml',
        'views/user_id_view.xml',
    ],
    'post_init_hook': 'post_init_hook',
    'auto_install': False,
    'application': False,
    'sequence': 0,
}
